name: Ejecutar tarea cron cada 10 minutos

on:
  schedule:
    - cron: "*/5 * * * *"  # cada 5 minutos (UTC)
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar endpoint protegido con token
        run: |
          curl -X GET "https://test-logs2.onrender.com/api/tarea-secreta?token=${{ secrets.CRON_TOKEN }}"
